`Simple Autoregressive Conditional Heteroskedasticity`

In [1]:
import numpy as np

import statsmodels.api as sm

In [2]:
np.random.seed(100)

total = 1000

eps = np.random.randn(total)

eps[:5]

array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079])

In [3]:
sigma = np.zeros(total)

sigma[:5]

array([0., 0., 0., 0., 0.])

In [4]:
sigma[0] = 0.05

for i in range(1, total):
  sigma[i] = 0.01 + 0.8 * sigma[i - 1] + 0.2 * np.power(eps[i - 1], 2)

sigma[:5]

array([0.05      , 0.66233584, 0.56335465, 0.72658203, 0.60401041])

In [5]:
returns = np.sqrt(sigma) * eps

returns[:5]

array([-0.39125945,  0.27888708,  0.86543356, -0.21517593,  0.76266394])